services:
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ratiaharivoav
      POSTGRES_PASSWORD: root905H-F
      POSTGRES_DB: pg17
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ratiaharivoav@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root905H-F
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    restart: always

volumes:
  pgadmin-data:
  postgres-data:
